services:
  # 1. BASE DE DATOS (Postgres)
  db:
    image: postgres:15
    container_name: gym_db_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Puedes cambiarlo
      POSTGRES_DB: gimnasio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 2. BACKEND (Tu API Java)
  api:
    image: amazoncorretto:21 # Usamos JRE (versión ligera para ejecutar)
    container_name: gym_api_prod
    volumes:
      - ./app.jar:/app/app.jar  # Aquí conectamos tu archivo
    command: java -jar /app/app.jar
    ports:
      - "0.0.0.0:8080:8080"  # Escuchar en todas las interfaces de red
    environment:
      # Conectamos con el servicio 'db' definido arriba
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gimnasio_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_ADDRESS: 0.0.0.0  # Aceptar conexiones desde cualquier IP
    depends_on:
      - db
    restart: always

  # 3. FRONTEND (Tu Web Flutter)
  web:
    image: nginx:alpine
    container_name: gym_web_prod
    volumes:
      - ./web:/usr/share/nginx/html # Aquí conectamos tu carpeta web
    ports:
      - "0.0.0.0:80:80" # La web se verá en el puerto normal, accesible desde cualquier IP
    restart: always

volumes:
  postgres_data:
