services:
  database:
    image: 'postgres:15'           # Descarga Postgres versión 15
    container_name: gym_db_local   # Nombre para identificarlo
    environment:
      - POSTGRES_DB=gimnasio_db    # Nombre de la base de datos
      - POSTGRES_PASSWORD=password # Contraseña (para desarrollo está bien 'password')
      - POSTGRES_USER=postgres     # Usuario
    ports:
      - '5432:5432'                # Abre el puerto 5432 para que Java pueda entrar
    volumes:
      - db_data:/var/lib/postgresql/data # Esto evita que pierdas datos al reiniciar

volumes:
  db_data:                         # Definición del volumen